#!/bin/bash

# Split the PATH variable into an array using ':' as the delimiter
IFS=':' read -ra PATH_DIRS <<< "$PATH"

# Count the number of elements in the array
NUM_PATH_DIRS=${#PATH_DIRS[@]}

# Print the number of directories in the PATH
echo "$NUM_PATH_DIRS"
